name: 'Terraform GitHub Actions'
on:
  push:
    branches:
    - main

env:
  tf_version: 1.0
  tf_working_dir: '.'

jobs:
  terraform:
    name: 'Terraform'
    runs-on: ubuntu-latest
    steps:
      - name: configure gcloud
        id: config_gcloud
        uses: google-github-actions/setup-gcloud@master
        with:
          version: "latest"
          service_account_email: ${{ secrets.GCP_SA_EMAIL }}
          service_account_key: ${{ secrets.GCP_SA_KEY }}

      - name: checkout
        id: checkout_code
        uses: actions/checkout@v2

      - name: set GCP project
        id: config_project
        run: gcloud config set project aesthetic-fx-223420

      - name: "Terraform Init"
        id: terraform_init
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: 1.0
          tf_actions_comment: "false"
          tf_actions_working_dir: '.'
          tf_actions_subcommand: init
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}
      - name: "Terraform Validate"
        id: terraform_validate
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: 1.0
          tf_actions_comment: "false"
          tf_actions_working_dir: '.'
          tf_actions_subcommand: validate
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}} 
      - name: "Terraform Plan"
        id: terraform_plan
        uses: ops18/terraform-github-actions@master
        with:
          tf_actions_version: 1.0
          tf_actions_comment: "false"
          tf_actions_working_dir: '.'
          tf_actions_subcommand: plan
        env:
          GCP_SA_KEY: ${{ secrets.GCP_SA_KEY}}